// <auto-generated />
using System;
using CleanArchitectureTemplate.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CleanArchitectureTemplate.Persistence.Migrations
{
    [DbContext(typeof(EfDbContext))]
    partial class EfDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CleanArchitectureTemplate.Domain.Entities.WeatherForecast", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("DATE")
                        .HasColumnName("Date");

                    b.Property<string>("Summary")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("Summary");

                    b.HasKey("Id")
                        .HasName("PK_WeatherForecast");

                    b.ToTable("weather_forecasts", (string)null);
                });

            modelBuilder.Entity("CleanArchitectureTemplate.Domain.Entities.WeatherForecast", b =>
                {
                    b.OwnsOne("CleanArchitectureTemplate.Domain.ValueObjects.Temperature", "Temperature", b1 =>
                        {
                            b1.Property<int>("WeatherForecastId")
                                .HasColumnType("integer");

                            b1.Property<int>("Celsius")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Celsius");

                            b1.Property<int>("Fahrenheit")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Fahrenheit");

                            b1.HasKey("WeatherForecastId");

                            b1.ToTable("weather_forecasts");

                            b1.WithOwner()
                                .HasForeignKey("WeatherForecastId");
                        });

                    b.Navigation("Temperature")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
