// <auto-generated />
using System;
using CleanArchitectureTemplate.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CleanArchitectureTemplate.Persistence.Migrations
{
    [DbContext(typeof(EfDbContext))]
    partial class EfDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("weather")
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CleanArchitectureTemplate.Domain.Entities.WeatherForecast", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("Integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("Date")
                        .HasColumnName("date");

                    b.Property<string>("Summary")
                        .HasMaxLength(200)
                        .HasColumnType("Text")
                        .HasColumnName("summary");

                    b.HasKey("Id")
                        .HasName("pk_forecast");

                    b.ToTable("forecast", "weather");
                });

            modelBuilder.Entity("CleanArchitectureTemplate.Domain.Entities.WeatherForecast", b =>
                {
                    b.OwnsOne("CleanArchitectureTemplate.Domain.ValueObjects.Temperature", "Temperature", b1 =>
                        {
                            b1.Property<int>("WeatherForecastId")
                                .HasColumnType("Integer");

                            b1.Property<int>("Celsius")
                                .HasColumnType("Integer")
                                .HasColumnName("celsius");

                            b1.Property<int>("Fahrenheit")
                                .HasColumnType("Integer")
                                .HasColumnName("fahrenheit");

                            b1.HasKey("WeatherForecastId");

                            b1.ToTable("forecast", "weather");

                            b1.WithOwner()
                                .HasForeignKey("WeatherForecastId");
                        });

                    b.Navigation("Temperature")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
